/* Generated By:JJTree: Do not edit this line. ASTAndExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTAndExpr extends LittleJavaNode {
  public ASTAndExpr(int id) {
    super(id);
  }

  public ASTAndExpr(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=48a95070bde05636572fcf0ebec7bc61 (do not edit this line) */
