/* Generated By:JJTree: Do not edit this line. ASTAssignExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTAssignExpr extends SimpleNode {
  public ASTAssignExpr(int id) {
    super(id);
  }

  public ASTAssignExpr(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=300f5dad59cc3e2df9ea1e8c882a5ef5 (do not edit this line) */
