/* Generated By:JJTree: Do not edit this line. ASTClassDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTClassDecl extends LittleJavaNode {
  public ASTClassDecl(int id) {
    super(id);
  }

  public ASTClassDecl(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a765fcc17dca6a5cde839ae9ae8e53a9 (do not edit this line) */
