/* Generated By:JJTree: Do not edit this line. ASTForInitSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTForInitSection extends SimpleNode {
  public ASTForInitSection(int id) {
    super(id);
  }

  public ASTForInitSection(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=532cc5773909856b177973a97e6a0f5e (do not edit this line) */
