/* Generated By:JJTree: Do not edit this line. ASTIfElseSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTIfElseSection extends LittleJavaNode {
  public ASTIfElseSection(int id) {
    super(id);
  }

  public ASTIfElseSection(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=37790816c6c3c064672a980a946051c3 (do not edit this line) */
