/* Generated By:JJTree: Do not edit this line. ASTIfExecuteSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTIfExecuteSection extends SimpleNode {
  public ASTIfExecuteSection(int id) {
    super(id);
  }

  public ASTIfExecuteSection(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6f393a4be4c3f6fec42dd48c88481617 (do not edit this line) */
