/* Generated By:JJTree: Do not edit this line. ASTLeftHandValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTLeftHandValue extends SimpleNode {
  public ASTLeftHandValue(int id) {
    super(id);
  }

  public ASTLeftHandValue(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6cf4f1e44ff4cc20452576b4ca4641fd (do not edit this line) */
