/* Generated By:JJTree: Do not edit this line. ASTMulExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTMulExpr extends SimpleNode {
  public ASTMulExpr(int id) {
    super(id);
  }

  public ASTMulExpr(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eedc8afc01bbc6ca2f58a1163127e52c (do not edit this line) */
