/* Generated By:JJTree: Do not edit this line. ASTMemberFunctionDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTMemberFunctionDeclaration extends LittleJavaNode {
  public ASTMemberFunctionDeclaration(int id) {
    super(id);
  }

  public ASTMemberFunctionDeclaration(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7fbf51863fb54bce0290e4149c3c18e3 (do not edit this line) */
