/* Generated By:JJTree: Do not edit this line. ASTMemberVariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTMemberVariableDeclaration extends LittleJavaNode {
  public ASTMemberVariableDeclaration(int id) {
    super(id);
  }

  public ASTMemberVariableDeclaration(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=80b78d3f4388113609b20c65f28d5b90 (do not edit this line) */
