/* Generated By:JJTree: Do not edit this line. ASTMethodDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTMethodDecl extends LittleJavaNode {
  public ASTMethodDecl(int id) {
    super(id);
  }

  public ASTMethodDecl(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5a26dbef9978d4efcc2e1af502239063 (do not edit this line) */
