/* Generated By:JavaCC: Do not edit this line. LittleJavaVisitor.java Version 5.0 */
package raw;

public interface LittleJavaVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTClassDecl node, Object data);
  public Object visit(ASTMemberVariableDeclaration node, Object data);
  public Object visit(ASTMemberFunctionDeclaration node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTReturnStatement node, Object data);
  public Object visit(ASTBreakStatement node, Object data);
  public Object visit(ASTContinueStatement node, Object data);
  public Object visit(ASTBlockStatement node, Object data);
  public Object visit(ASTLocalVariableDeclaration node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTIfConditionSection node, Object data);
  public Object visit(ASTIfExecuteSection node, Object data);
  public Object visit(ASTIfElseSection node, Object data);
  public Object visit(ASTWhileStatement node, Object data);
  public Object visit(ASTForStatement node, Object data);
  public Object visit(ASTForInitSection node, Object data);
  public Object visit(ASTForExecuteSection node, Object data);
  public Object visit(ASTAssignExpr node, Object data);
  public Object visit(ASTOrExpr node, Object data);
  public Object visit(ASTAndExpr node, Object data);
  public Object visit(ASTEquExpr node, Object data);
  public Object visit(ASTRelExpr node, Object data);
  public Object visit(ASTAddExpr node, Object data);
  public Object visit(ASTMulExpr node, Object data);
  public Object visit(ASTRightHandValue node, Object data);
  public Object visit(ASTLeftHandValue node, Object data);
  public Object visit(ASTArgumentList node, Object data);
  public Object visit(ASTParameterList node, Object data);
}
/* JavaCC - OriginalChecksum=f3c5780ba4cbe37326853b17568cc5ae (do not edit this line) */
