/* Generated By:JJTree: Do not edit this line. ASTForExecuteSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTForExecuteSection extends LittleJavaNode {
  public ASTForExecuteSection(int id) {
    super(id);
  }

  public ASTForExecuteSection(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ba9554bf02e7502c8947ac419adad9ce (do not edit this line) */
