/* Generated By:JJTree: Do not edit this line. ASTIfConditionSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTIfConditionSection extends LittleJavaNode {
  public ASTIfConditionSection(int id) {
    super(id);
  }

  public ASTIfConditionSection(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=03e00010900c2bfab784a73fc31bb48a (do not edit this line) */
