/* Generated By:JJTree: Do not edit this line. ASTIfExecuteSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTIfExecuteSection extends LittleJavaNode {
  public ASTIfExecuteSection(int id) {
    super(id);
  }

  public ASTIfExecuteSection(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e9830a5ff7e7c51d5ffcc3235894ea65 (do not edit this line) */
