/* Generated By:JJTree: Do not edit this line. ASTReturnType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTReturnType extends LittleJavaNode {
  public ASTReturnType(int id) {
    super(id);
  }

  public ASTReturnType(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=571111a34b855e17bcc4838e6b2a2a74 (do not edit this line) */
