/* Generated By:JJTree: Do not edit this line. ASTRightHandValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package raw;

public
class ASTRightHandValue extends LittleJavaNode {
  public ASTRightHandValue(int id) {
    super(id);
  }

  public ASTRightHandValue(LittleJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LittleJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c7022187d6a53fe783f504dd621d2116 (do not edit this line) */
