/* Generated By:JavaCC: Do not edit this line. LittleJavaTreeConstants.java Version 5.0 */
package raw;

public interface LittleJavaTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCLASSDECL = 1;
  public int JJTMEMBERVARIABLEDECLARATION = 2;
  public int JJTMEMBERFUNCTIONDECLARATION = 3;
  public int JJTRETURNTYPE = 4;
  public int JJTTYPE = 5;
  public int JJTVOID = 6;
  public int JJTRETURNSTATEMENT = 7;
  public int JJTBREAKSTATEMENT = 8;
  public int JJTCONTINUESTATEMENT = 9;
  public int JJTBLOCKSTATEMENT = 10;
  public int JJTLOCALVARIABLEDECLARATION = 11;
  public int JJTIFSTATEMENT = 12;
  public int JJTIFCONDITIONSECTION = 13;
  public int JJTIFEXECUTESECTION = 14;
  public int JJTIFELSESECTION = 15;
  public int JJTWHILESTATEMENT = 16;
  public int JJTFORSTATEMENT = 17;
  public int JJTFORINITSECTION = 18;
  public int JJTFOREXECUTESECTION = 19;
  public int JJTASSIGNEXPR = 20;
  public int JJTOREXPR = 21;
  public int JJTANDEXPR = 22;
  public int JJTEQUEXPR = 23;
  public int JJTRELEXPR = 24;
  public int JJTADDEXPR = 25;
  public int JJTMULEXPR = 26;
  public int JJTRIGHTHANDVALUE = 27;
  public int JJTLEFTHANDVALUE = 28;
  public int JJTARGUMENTLIST = 29;
  public int JJTPARAMETERLIST = 30;


  public String[] jjtNodeName = {
    "Start",
    "ClassDecl",
    "MemberVariableDeclaration",
    "MemberFunctionDeclaration",
    "ReturnType",
    "Type",
    "void",
    "ReturnStatement",
    "BreakStatement",
    "ContinueStatement",
    "BlockStatement",
    "LocalVariableDeclaration",
    "IfStatement",
    "IfConditionSection",
    "IfExecuteSection",
    "IfElseSection",
    "WhileStatement",
    "ForStatement",
    "ForInitSection",
    "ForExecuteSection",
    "AssignExpr",
    "OrExpr",
    "AndExpr",
    "EquExpr",
    "RelExpr",
    "AddExpr",
    "MulExpr",
    "RightHandValue",
    "LeftHandValue",
    "ArgumentList",
    "ParameterList",
  };
}
/* JavaCC - OriginalChecksum=3ab9e67bc8b6e6826bf9710893bce031 (do not edit this line) */
