/* Generated By:JJTree: Do not edit this line. ASTClassDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDecl extends SimpleNode {
  public ASTClassDecl(int id) {
    super(id);
  }

  public ASTClassDecl(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=43e0a3c6601e0b13334148959640e5d3 (do not edit this line) */
