/* Generated By:JJTree: Do not edit this line. ASTForInitSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTForInitSection extends SimpleNode {
  public ASTForInitSection(int id) {
    super(id);
  }

  public ASTForInitSection(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f8782b8f0b9c83d4c93f2a24f6ece366 (do not edit this line) */
