/* Generated By:JJTree: Do not edit this line. ASTIfElseSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfElseSection extends SimpleNode {
  public ASTIfElseSection(int id) {
    super(id);
  }

  public ASTIfElseSection(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0f7f4fa1fce483475f1d92b70d129b77 (do not edit this line) */
