/* Generated By:JJTree: Do not edit this line. ASTIfConditionSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfConditionSection extends SimpleNode {
  public ASTIfConditionSection(int id) {
    super(id);
  }

  public ASTIfConditionSection(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84a7ed6228d608d4112e7d6173ef8ea0 (do not edit this line) */
