/* Generated By:JJTree: Do not edit this line. ASTIfMainSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfMainSection extends SimpleNode {
  public ASTIfMainSection(int id) {
    super(id);
  }

  public ASTIfMainSection(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d483e3ef593ff8224131befae59e60e (do not edit this line) */
