/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclarationStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLocalVariableDeclarationStatement extends SimpleNode {
  public ASTLocalVariableDeclarationStatement(int id) {
    super(id);
  }

  public ASTLocalVariableDeclarationStatement(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46330c873a7200ec5663a3022f35df4a (do not edit this line) */
