/* Generated By:JJTree: Do not edit this line. ASTMulExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMulExpr extends SimpleNode {
  public ASTMulExpr(int id) {
    super(id);
  }

  public ASTMulExpr(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90d2630e3be8ea5f35d350b19243de41 (do not edit this line) */
