/* Generated By:JJTree: Do not edit this line. ASTRightHandValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRightHandValue extends SimpleNode {
  public ASTRightHandValue(int id) {
    super(id);
  }

  public ASTRightHandValue(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=482effdb51c2f259e4ed52faa4905fe2 (do not edit this line) */
