/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDecl extends SimpleNode {
  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(LittleJava p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1ef865d228ef02a0d1188d26a83cd51a (do not edit this line) */
