/* Generated By:JavaCC: Do not edit this line. LittleJavaTreeConstants.java Version 5.0 */
public interface LittleJavaTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCLASSDECL = 1;
  public int JJTVOID = 2;
  public int JJTMEMBERVARIABLEDECLARATION = 3;
  public int JJTMEMBERFUNCTIONDECLARATION = 4;
  public int JJTTYPE = 5;
  public int JJTBLOCKSTATEMENT = 6;
  public int JJTRETURNSTATEMENT = 7;
  public int JJTBREAKSTATEMENT = 8;
  public int JJTCONTINUESTATEMENT = 9;
  public int JJTLOCALVARIABLEDECLARATIONSTATEMENT = 10;
  public int JJTIFSTATEMENT = 11;
  public int JJTIFCONDITIONSECTION = 12;
  public int JJTIFMAINSECTION = 13;
  public int JJTIFELSESECTION = 14;
  public int JJTWHILESTATEMENT = 15;
  public int JJTASSIGNEXPR = 16;
  public int JJTOREXPR = 17;
  public int JJTANDEXPR = 18;
  public int JJTEQUEXPR = 19;
  public int JJTRELEXPR = 20;
  public int JJTADDEXPR = 21;
  public int JJTMULEXPR = 22;
  public int JJTRIGHTHANDVALUE = 23;
  public int JJTLEFTHANDVALUE = 24;


  public String[] jjtNodeName = {
    "Start",
    "ClassDecl",
    "void",
    "MemberVariableDeclaration",
    "MemberFunctionDeclaration",
    "Type",
    "BlockStatement",
    "ReturnStatement",
    "BreakStatement",
    "ContinueStatement",
    "LocalVariableDeclarationStatement",
    "IfStatement",
    "IfConditionSection",
    "IfMainSection",
    "IfElseSection",
    "WhileStatement",
    "AssignExpr",
    "OrExpr",
    "AndExpr",
    "EquExpr",
    "RelExpr",
    "AddExpr",
    "MulExpr",
    "RightHandValue",
    "LeftHandValue",
  };
}
/* JavaCC - OriginalChecksum=4e660d13acc7cb110e32ffbbd275859e (do not edit this line) */
