/* Generated By:JavaCC: Do not edit this line. LittleJavaTreeConstants.java Version 5.0 */
public interface LittleJavaTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCLASSDECL = 1;
  public int JJTVOID = 2;
  public int JJTVARDECL = 3;
  public int JJTMETHODDECL = 4;
  public int JJTTYPE = 5;


  public String[] jjtNodeName = {
    "Start",
    "ClassDecl",
    "void",
    "VarDecl",
    "MethodDecl",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=00ca16b0df48583456adcae8d04dad24 (do not edit this line) */
