package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTAndExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAndExpr extends SimpleNode {
	public ASTAndExpr(int id) {
		super(id);
	}

	public ASTAndExpr(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=665ddaaf36a30ad9a4dcee14452a25cb (do not edit this
 * line)
 */
