package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTAssignExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAssignExpr extends SimpleNode {
	public ASTAssignExpr(int id) {
		super(id);
	}

	public ASTAssignExpr(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=a02392c15ae0750690d289364870ea26 (do not edit this
 * line)
 */
