package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTAddExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAddExpr extends SimpleNode {
	public ASTAddExpr(int id) {
		super(id);
	}

	public ASTAddExpr(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=8aafa68b7ea5160f2945b9e8c6205add (do not edit this
 * line)
 */
