package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTBlockStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTBlockStatement extends SimpleNode {
	public ASTBlockStatement(int id) {
		super(id);
	}

	public ASTBlockStatement(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=c1048778e2db482331ebf0bf49fe80f5 (do not edit this
 * line)
 */
