package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTDecl extends SimpleNode {
	public ASTDecl(int id) {
		super(id);
	}

	public ASTDecl(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=6851e8edeb63e67c13dfcedffd988dd3 (do not edit this
 * line)
 */
