package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTEquExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTEquExpr extends SimpleNode {
	public ASTEquExpr(int id) {
		super(id);
	}

	public ASTEquExpr(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=a0af6a7a0170fa7a255bf2ba6676a166 (do not edit this
 * line)
 */
