package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTForExecuteSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTForExecuteSection extends SimpleNode {
	public ASTForExecuteSection(int id) {
		super(id);
	}

	public ASTForExecuteSection(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=f7b76eeb6a329ae25f65dcfb846c0787 (do not edit this
 * line)
 */
