package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTForStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTForStatement extends SimpleNode {
	public ASTForStatement(int id) {
		super(id);
	}

	public ASTForStatement(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=bdb985ca27b07135eebefce29aa3f76b (do not edit this
 * line)
 */
