package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTIfExecuteSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIfExecuteSection extends SimpleNode {
	public ASTIfExecuteSection(int id) {
		super(id);
	}

	public ASTIfExecuteSection(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=0822604ca1c95946dcca34991f2cc335 (do not edit this
 * line)
 */
