package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTLeftHandValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTLeftHandValue extends SimpleNode {
	public ASTLeftHandValue(int id) {
		super(id);
	}

	public ASTLeftHandValue(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=6630aba74a2c4a9ac31679cb674f4b86 (do not edit this
 * line)
 */
