package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTMemberVariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMemberVariableDeclaration extends SimpleNode {
	public ASTMemberVariableDeclaration(int id) {
		super(id);
	}

	public ASTMemberVariableDeclaration(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=698ef71f9667ef5ad257d1ff0e0db3c4 (do not edit this
 * line)
 */
