package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTMemberFunctionDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMemberFunctionDeclaration extends SimpleNode {
	public ASTMemberFunctionDeclaration(int id) {
		super(id);
	}

	public ASTMemberFunctionDeclaration(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=718615b464b60f3b98f5303084afc622 (do not edit this
 * line)
 */
