package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTMethodDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMethodDecl extends SimpleNode {
	public ASTMethodDecl(int id) {
		super(id);
	}

	public ASTMethodDecl(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=69a6b67e7f7e474112f3c79973c039f8 (do not edit this
 * line)
 */
