package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTOrExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTOrExpr extends SimpleNode {
	public ASTOrExpr(int id) {
		super(id);
	}

	public ASTOrExpr(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=d09f7f732e4df8dcf73fd8a0da0aa8d6 (do not edit this
 * line)
 */
