package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTParameterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTParameterList extends SimpleNode {
	public ASTParameterList(int id) {
		super(id);
	}

	public ASTParameterList(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=a1528a8ef5f975d317a4c8887ae584ef (do not edit this
 * line)
 */
