package CompilerForeEnd;
/* Generated By:JJTree: Do not edit this line. ASTRelExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTRelExpr extends SimpleNode {
	public ASTRelExpr(int id) {
		super(id);
	}

	public ASTRelExpr(LittleJava p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=434fb15a7dfe2a2d0f3979d5ae3c0042 (do not edit this
 * line)
 */
