package CompilerForeEnd;
/* Generated By:JavaCC: Do not edit this line. LittleJavaTreeConstants.java Version 5.0 */
public interface LittleJavaTreeConstants {
	public int JJTSTART = 0;
	public int JJTCLASSDECL = 1;
	public int JJTVOID = 2;
	public int JJTMEMBERVARIABLEDECLARATION = 3;
	public int JJTMEMBERFUNCTIONDECLARATION = 4;
	public int JJTTYPE = 5;
	public int JJTRETURNSTATEMENT = 6;
	public int JJTBREAKSTATEMENT = 7;
	public int JJTCONTINUESTATEMENT = 8;
	public int JJTBLOCKSTATEMENT = 9;
	public int JJTLOCALVARIABLEDECLARATION = 10;
	public int JJTIFSTATEMENT = 11;
	public int JJTIFCONDITIONSECTION = 12;
	public int JJTIFEXECUTESECTION = 13;
	public int JJTIFELSESECTION = 14;
	public int JJTWHILESTATEMENT = 15;
	public int JJTFORSTATEMENT = 16;
	public int JJTFORINITSECTION = 17;
	public int JJTFOREXECUTESECTION = 18;
	public int JJTASSIGNEXPR = 19;
	public int JJTOREXPR = 20;
	public int JJTANDEXPR = 21;
	public int JJTEQUEXPR = 22;
	public int JJTRELEXPR = 23;
	public int JJTADDEXPR = 24;
	public int JJTMULEXPR = 25;
	public int JJTRIGHTHANDVALUE = 26;
	public int JJTLEFTHANDVALUE = 27;
	public int JJTARGUMENTLIST = 28;
	public int JJTPARAMETERLIST = 29;

	public String[] jjtNodeName = { "Start", "ClassDecl", "void",
			"MemberVariableDeclaration", "MemberFunctionDeclaration", "Type",
			"ReturnStatement", "BreakStatement", "ContinueStatement",
			"BlockStatement", "LocalVariableDeclaration", "IfStatement",
			"IfConditionSection", "IfExecuteSection", "IfElseSection",
			"WhileStatement", "ForStatement", "ForInitSection",
			"ForExecuteSection", "AssignExpr", "OrExpr", "AndExpr", "EquExpr",
			"RelExpr", "AddExpr", "MulExpr", "RightHandValue", "LeftHandValue",
			"ArgumentList", "ParameterList", };
}
/*
 * JavaCC - OriginalChecksum=321ab6519406a0134fc76ed08a3eec19 (do not edit this
 * line)
 */
